version: '3'

services:
  db:
    image: supabase/postgres:15.1.0.112
    restart: always
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      # Must be superuser to create event trigger
      - ./volumes/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      # Must be superuser to alter reserved role
      - ./volumes/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      # Changes required for Analytics support
      - ./volumes/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z
      - db-data:/var/lib/postgresql/data:Z

volumes:
  db-data: {}
