packages:
  - apps/*
  - packages/*

engineStrict: true

onlyBuiltDependencies:
  - "@confluentinc/kafka-javascript"
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - bcrypt
  - bufferutil
  - cypress
  - esbuild
  - nestjs-pino
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  "@auth/core@0.41.0": "@auth/core@0.41.1"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  qs@<6.14.1: ">=6.14.1"
  systeminformation@<5.27.14: ">=5.27.14"
  tar@<=7.5.3: ">=7.5.4"
