packages:
  - apps/*
  - packages/*

engineStrict: true

onlyBuiltDependencies:
  - "@confluentinc/kafka-javascript"
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - bcrypt
  - bufferutil
  - cypress
  - esbuild
  - nestjs-pino
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  "@auth/core@0.41.0": "@auth/core@0.41.1"
  diff@>=4.0.0 <4.0.4: ">=4.0.4"
  diff@>=5.0.0 <5.2.2: ">=5.2.2"
  fast-xml-parser@>=4.1.3 <5.3.6: ">=5.3.6"
  fastify@<=5.7.2: ">=5.7.3"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@<10.2.1: ">=10.2.1"
  qs@<6.14.1: ">=6.14.1"
  systeminformation@<5.30.8: ">=5.31.0"
  tar@<7.5.8: ">=7.5.8"
  undici@<6.23.0: ">=6.23.0"
