services:
  redis:
    image: my-redis
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - ${REDIS_PORT}:6379

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    external: true