services:
  redis:
    image: redis:8.8
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    external: true
