services:
  nginx:
    image: nginx:1.30.3
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:8080
    environment:
      NGINX_BACKEND_HOST: ${NGINX_BACKEND_HOST}
      NGINX_WEBSOCKET_HOST: ${NGINX_WEBSOCKET_HOST}
    volumes:
      - ./templates:/etc/nginx/templates
