export const links = {
  twitter: "https://x.com/flows_sh",
  rbnd: "https://rbnd.studio",
  rbndGithub: "https://github.com/RBND-studio",
  status: "https://status.flows.sh",
  slack: "https://flows.sh/join-slack",
  signUp: "https://app.flows.sh/signup",
  logIn: "https://app.flows.sh/login",
  nextJsDemo: "https://nextjs.flows.sh",
  privacy: "https://flows.sh/privacy",
  terms: "https://flows.sh/terms",
  pricing: "https://flows.sh/pricing",
  changelog: "https://flows.sh/changelog",
  // docs
  docs: "https://flows.sh/docs",
  docsStepsEditor: "https://flows.sh/docs/creating-flows/steps-editor",
  docsInstallFlows: "https://flows.sh/docs/getting-started/install-flows",
  docsVerifyInstallation: "https://flows.sh/docs/getting-started/install-flows#verify-installation",
  docsContact: "https://flows.sh/docs/contact-us",
};
