// eslint-disable-next-line @typescript-eslint/explicit-function-return-type -- infer the return type
export const links = (domain = "flows.sh") => ({
  homePage: `https://${domain}`,
  twitter: `https://x.com/flows_sh`,
  rbnd: `https://rbnd.studio`,
  rbndGithub: `https://github.com/RBND-studio`,
  status: `https://status.flows.sh`,
  slack: `https://flows.sh/join-slack`,
  signUp: `https://app.${domain}/signup`,
  logIn: `https://app.${domain}/login`,
  nextJsDemo: `https://nextjs.flows.sh`,
  privacy: `https://${domain}/privacy`,
  terms: `https://${domain}/terms`,
  pricing: `https://${domain}/pricing`,
  changelog: `https://${domain}/changelog`,
  demoVideoEmbed: `https://www.youtube.com/embed/XY3eU_p0AW4?si=kSQJFruZM8YViA0w`,
  demoVideo: `https://youtu.be/XY3eU_p0AW4?si=I-Kws9rhJ9RLak7Q`,
  docs: {
    home: `https://${domain}/docs`,
    stepsEditor: `https://${domain}/docs/creating-flows/steps-editor`,
    installFlows: `https://${domain}/docs/getting-started/install-flows`,
    contact: `https://${domain}/docs/contact-us`,
    startFlow: `https://${domain}/docs/creating-flows/start-flow`,
    targetFlow: `https://${domain}/docs/creating-flows/targeting`,
    flowFrequency: `https://${domain}/docs/creating-flows/frequency`,
    step: {
      tooltip: `https://${domain}/docs/step-types/tooltip`,
      modal: `https://${domain}/docs/step-types/modal`,
      banner: `https://${domain}/docs/step-types/banner`,
      wait: `https://${domain}/docs/step-types/wait`,
    },
    branchTargeting: `https://${domain}/docs/step-types/fork#targeting-branches`,
    previewFlow: `https://${domain}/docs/creating-flows/preview`,
    publishFlow: `https://${domain}/docs/creating-flows/enable-flow#publishing-changes`,
    makeFlowLive: `https://${domain}/docs/creating-flows/enable-flow#making-your-flow-live`,
    projectDomains: `https://${domain}/docs/project-setup/project-domains`,
    customStyles: `https://${domain}/docs/customization-and-styling/custom-styles`,
    migrateToFlows: `https://${domain}/docs/migrate-to-flows`,
    resetFlow: `https://${domain}/docs/project-setup/reset-user-progress`,
  },
});
