export const links = {
  twitter: "https://x.com/flows_sh",
  rbnd: "https://rbnd.studio",
  rbndGithub: "https://github.com/RBND-studio",
  status: "https://status.flows.sh",
  slack: "https://flows.sh/join-slack",
  signUp: "https://app.flows.sh/signup",
  logIn: "https://app.flows.sh/login",
  nextJsDemo: "https://nextjs.flows.sh",
  privacy: "https://flows.sh/privacy",
  terms: "https://flows.sh/terms",
  pricing: "https://flows.sh/pricing",
  changelog: "https://flows.sh/changelog",
  docs: {
    home: "https://flows.sh/docs",
    stepsEditor: "https://flows.sh/docs/creating-flows/steps-editor",
    installFlows: "https://flows.sh/docs/getting-started/install-flows",
    contact: "https://flows.sh/docs/contact-us",
    startFlow: "https://flows.sh/docs/creating-flows/start-flow",
    targetFlow: "https://flows.sh/docs/creating-flows/targeting",
    flowFrequency: "https://flows.sh/docs/creating-flows/frequency",
    step: {
      tooltip: "https://flows.sh/docs/step-types/tooltip",
      modal: "https://flows.sh/docs/step-types/modal",
      wait: "https://flows.sh/docs/step-types/wait",
    },
    branchTargeting: "https://flows.sh/docs/step-types/fork#targeting-branches",
    previewFlow: "https://flows.sh/docs/creating-flows/preview",
    publishFlow: "https://flows.sh/docs/creating-flows/enable-flow#publishing-changes",
    makeFlowLive: "https://flows.sh/docs/creating-flows/enable-flow#making-your-flow-live",
    projectDomains: "https://flows.sh/docs/project-setup/project-domains",
    customStyles: "https://flows.sh/docs/customization-and-styling/custom-styles",
    migrateToFlows: "https://flows.sh/docs/migrate-to-flows",
  },
};
