import { Box, Flex } from "@flows/styled-system/jsx";
import { type JSX } from "react";

export const LayoutIllustration = (): JSX.Element => {
  return (
    <Flex
      width="100%"
      gap="space8"
      height={200}
      overflow="hidden"
      role="img"
      aria-label="A visual representation of a layout with a Flows slot in the center, surrounded by other components, including a sidebar, header, and content area."
    >
      <Box
        flex={1}
        background="bg.neutral.muted"
        borderWidth="1px"
        borderColor="border.neutral.muted"
        borderBottom={0}
        borderTopRadius="radius6"
        aria-hidden="true"
      />
      <Flex flexDirection="column" flex={1} gap="space8" aria-hidden="true">
        <Box
          flex={1}
          borderWidth="1px"
          borderColor="border.neutral.strong"
          borderStyle="dashed"
          borderRadius="radius6"
          aria-hidden="true"
        />
        <Box
          flex={1}
          background="bg.neutral.muted"
          borderWidth="1px"
          borderColor="border.neutral.muted"
          borderBottom={0}
          borderTopRadius="radius6"
          aria-hidden="true"
        />
      </Flex>
      <Box
        flex={1}
        background="bg.neutral.muted"
        borderWidth="1px"
        borderColor="border.neutral.muted"
        borderBottom={0}
        borderTopRadius="radius6"
        aria-hidden="true"
      />
      <Box
        flex={1}
        background="bg.neutral.muted"
        borderWidth="1px"
        borderColor="border.neutral.muted"
        borderBottom={0}
        borderTopRadius="radius6"
        aria-hidden="true"
      />
      <Box
        flex={1}
        background="bg.neutral.muted"
        borderWidth="1px"
        borderColor="border.neutral.muted"
        borderBottom={0}
        borderTopRadius="radius6"
        aria-hidden="true"
      />
      <Box
        flex={1}
        background="bg.neutral.muted"
        borderWidth="1px"
        borderColor="border.neutral.muted"
        borderBottom={0}
        borderTopRadius="radius6"
        aria-hidden="true"
      />
    </Flex>
  );
};
