import "./globals.css";

import { ConfigProvider } from "contexts/config-context";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "E2E Demo | Flows",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body>
        <ConfigProvider>{children}</ConfigProvider>
      </body>
    </html>
  );
}
