import "./globals.css";

import { css } from "@flows/styled-system/css";
import { Flex } from "@flows/styled-system/jsx";
import { PlaceholderApplication } from "components/placeholder-application";
import { ConfigProvider } from "contexts/config-context";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "E2E Demo | Flows",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className={css({ layerStyle: "dotBackground" })}>
      <body>
        <ConfigProvider>
          <Flex height="100vh" alignItems="center">
            <Flex height="560px" flex={1} justifyContent="center">
              <PlaceholderApplication>{children}</PlaceholderApplication>
            </Flex>
          </Flex>
        </ConfigProvider>
      </body>
    </html>
  );
}
